# Generated by Django 3.2.6 on 2021-08-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Nombre de la unidad.", max_length=50)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Índice de la unidad (para ordenar, de manera interna).", unique=True
                    ),
                ),
                (
                    "goal",
                    models.CharField(default="Ejemplo", help_text="Objetivo de la materia.", max_length=200),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="SubUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Nombre de la unidad.", max_length=50)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Índice de la unidad (para ordenar, de manera interna).", unique=True
                    ),
                ),
                ("contents", models.TextField(help_text="Contenidos (html).", max_length=100000)),
                (
                    "order_as_str",
                    models.CharField(
                        help_text="Índice a mostrar en el sitio (Ej: 1.2.3).", max_length=10, unique=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="Sección padre de esta subunidad.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SubUnit",
                        to="gestion.unit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
