# Generated by Django 3.2.6 on 2021-08-27 18:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0005_subunit_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subunit",
            name="contents",
            field=tinymce.models.HTMLField(),
        ),
    ]
