# Generated by Django 3.2.6 on 2022-04-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0007_auto_20211126_1537"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subunit",
            name="name",
            field=models.CharField(
                help_text="Nombre de la unidad.",
                max_length=100,
                verbose_name="Nombre de la unidad",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(
                help_text="Nombre de la unidad.",
                max_length=100,
                verbose_name="Nombre de la unidad",
            ),
        ),
        migrations.AlterField(
            model_name="unitresource",
            name="name",
            field=models.CharField(
                help_text="Nombre de la unidad.",
                max_length=100,
                verbose_name="Nombre de la unidad",
            ),
        ),
    ]
