# Generated by Django 3.2.6 on 2022-04-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0009_glossary_inforesource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glossary",
            options={"ordering": ("term",), "verbose_name_plural": "Glossary terms"},
        ),
        migrations.RenameField(
            model_name="glossary",
            old_name="goal",
            new_name="description",
        ),
    ]
