# Generated by Django 3.2.6 on 2022-04-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20220404_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='description',
            field=models.TextField(help_text='Descripción de este término.', max_length=300),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='term',
            field=models.CharField(help_text='Término.', max_length=100),
        ),
        migrations.AlterField(
            model_name='inforesource',
            name='resource',
            field=models.TextField(help_text='Referencia a este recurso de información.', max_length=300),
        ),
    ]
