# Generated by Django 3.2.6 on 2022-05-20 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_auto_20220429_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunit',
            name='parent',
            field=models.ForeignKey(help_text='Sección padre de esta subunidad.', on_delete=django.db.models.deletion.CASCADE, to='gestion.unit', verbose_name='Sección padre'),
        ),
        migrations.AlterField(
            model_name='unitresource',
            name='parent',
            field=models.ForeignKey(help_text='Sección padre de este recurso.', on_delete=django.db.models.deletion.CASCADE, to='gestion.unit', verbose_name='Sección padre'),
        ),
        migrations.CreateModel(
            name='SelfAssesmentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Índice de la unidad (usado para ordenar cada unidad).', unique=True, verbose_name='Índice')),
                ('name', models.TextField(help_text='Nombre para este recurso', max_length=100)),
                ('contents', models.TextField(help_text='Contenidos (HTML) para este recurso.', max_length=1000)),
                ('file', models.FileField(upload_to='')),
                ('subtitle', models.TextField(blank=True, help_text='Subtítulo, opcional.', max_length=1000, null=True)),
                ('parent', models.ForeignKey(help_text='Sección padre de este recurso.', on_delete=django.db.models.deletion.CASCADE, to='gestion.unit', verbose_name='Sección padre')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Índice de la unidad (usado para ordenar cada unidad).', unique=True, verbose_name='Índice')),
                ('name', models.TextField(help_text='Nombre para este recurso', max_length=100)),
                ('contents', models.TextField(help_text='Contenidos (HTML) para este recurso.', max_length=1000)),
                ('file', models.FileField(upload_to='')),
                ('subtitle', models.TextField(blank=True, help_text='Subtítulo, opcional.', max_length=1000, null=True)),
                ('parent', models.ForeignKey(help_text='Sección padre de este recurso.', on_delete=django.db.models.deletion.CASCADE, to='gestion.unit', verbose_name='Sección padre')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
