# Generated by Django 3.2.6 on 2022-05-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_auto_20220520_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityresource',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='selfassesmentresource',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='activityresource',
            name='order',
        ),
        migrations.RemoveField(
            model_name='selfassesmentresource',
            name='order',
        ),
    ]
