# Generated by Django 3.2.6 on 2022-05-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_auto_20220520_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='assessment_resource',
        ),
    ]
